directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false
# Directories and files below will not be scanned at all
exclude_paths:
  - db/migrate/**